### PR TITLE
Add an arbitrary fuzzer

### PR DESCRIPTION
**Pull request by VTCAKAVSMoACE**
This was surprisingly quite simple thanks to the way you laid out the crate. This adds a fuzzer which generates arbitrary ASTs and compiles them to regex. While you certainly wouldn't want to use any of the regexes it generates (most are invalid because of the arbitrary String generation), you can use this to quickly verify that you won't encounter crashes during the transcompilation of melody to regex.

### CODE REVIEW

**Comment by yoav-lavi** [comment]
Looks really cool @VTCAKAVSMoACE! I'll be able to go over it more in depth later, but for now my one concern is that cargo-fuzz doesn't work for M1 macs. Would it be possible to configure this to run only in CI?

**Comment by yoav-lavi** [comment]
@VTCAKAVSMoACE Actually it does work on apple silicon, I misread the notice, disregard!

**Review by yoav-lavi — APPROVED** [review]

**Comment by yoav-lavi** [comment]
Looks good, thank you for your contribution!

**Comment by yoav-lavi** [comment]
@VTCAKAVSMoACE this seems to work correctly but the used memory by the test grows constantly, is this normally for a fuzz test or a memory leak?

**Comment by VTCAKAVSMoACE** [comment]
I suspect that what you're seeing is not a leak but rather the record of previous coverage which the fuzzer is using internally to identify "interesting" test cases.

Just to check, though, what flags are you using to run the fuzzer?

**Pull request merged**
