### PR TITLE
Add not digit, space, word syntax

### PR DESCRIPTION
**Pull request by Omikorin**

### CODE REVIEW

**Comment by yoav-lavi** [comment]
@Omikorin would be happy to merge this after it's updated to the current state of the repo (docs + playground + extensions also need to be updated)
Thank you for your contribution!

**Comment by Omikorin** [comment]
Ok, I'm in

**Comment by Omikorin** [comment]
@yoav-lavi done

**Comment by yoav-lavi** [comment]
Thank you @Omikorin, would you be willing to also update the docs/ and playground/ folders? Otherwise I can take it, just want to make sure they don't get out of sync.
Will merge later today, thank you for your contribution!

**Review by yoav-lavi — APPROVED** [review]

**Pull request merged**
