### PR TITLE
feat: deno module implementation

### PR DESCRIPTION
**Pull request by load1n9**
deno module implementation of melody

### CODE REVIEW

**Comment by load1n9** [comment]
By the way if you want to register it to the deno.land registry https://deno.land/x I would do this before you create any new versions

**Comment by yoav-lavi** [comment]
@load1n9 Haven't forgotten about this, I've been trying to create a sync version of the WASM bindings but it doesn't seem to work correctly (at least with the playground). For something like Deno / Node I want to avoid having an async interface

**Comment by load1n9** [comment]
If you would like help contact me on discord loading...#6605

**Comment by yoav-lavi** [comment]
Hey, ended up going with a bit of a different direction regarding the Deno module but I thank you for your contribution, would be happy to see future contributions!

**Pull request closed without merging**
